### ISSUE TITLE
Any plan to release a new version with Spring Boot 2.3.0 & GraalVM 20.1.0

### ISSUE THREAD

**Issue by linux-china** [making/rsc#16]
Spring Boot 2.3.0 with RSocket 1.0.0, and rsc could be 1.0.0. :)

**Comment by making** [comment]
I'll update it after 0.4.2 is released for #18

**Comment by making** [comment]
Updated to RSocket 1.0.0 and added `--retry` option.
For building with the latest GraalVM, I filed another issue #23 .
