### ISSUE TITLE
Follow alternate convention for graalvm artifacts

### ISSUE THREAD

**Issue by mushtaq** [making/rsc#29]
I have added entries to contrib channel of coursier for [rsc](https://github.com/coursier/apps/blob/master/apps-contrib/resources/rsc.json) and [rscj](https://github.com/coursier/apps/blob/master/apps-contrib/resources/rscj.json).

For Jvm community which have [coursier](https://get-coursier.io/docs/cli-installation) installed on their machine, this will simplify the binary installtion.
- Java binary can be installed as: `cs install rscj --contrib`
- On Mac, graalvm binary can be installed as: `cs install rsc --contrib`

For graalvm binaries to work, the generated artefacts must follow certain naming [convention](https://get-coursier.io/docs/cli-install.html#prebuilt). The new name need to be:
- rsc-x86_64-pc-linux (instead of rsc-linux-x86_64)
- rsc-x86_64-apple-darwin (instead of rsc-osx-x86_64)
- (in future) rsc-x86_64-pc-win32 (instead of rsc-win32-x86_64)

**Comment by mushtaq** [comment]
BTW, the jars are downloaded via [jitpack](https://jitpack.io/#making/rsc) because I did not find them on mavencentral.

**Comment by making** [comment]
Thanks. I'll rename artifacts to follow the convention from next release.

**Comment by making** [comment]
@mushtaq 
Changed filenames for 0.5.1
https://github.com/making/rsc/releases/tag/0.5.1

I have never used coursier. Can you please contribute the document how to install `rsc` using coursier?

**Comment by mushtaq** [comment]
Thanks!

I have proposed [the change](https://github.com/coursier/apps/pull/61/files) in the coursier channel. Once it is merged and released, which may take a few days, I will send you the README updates.
