### ISSUE TITLE
Windows error: MultipleArgumentsForOptionException

### ISSUE THREAD

**Issue by Huang-ChenGang** [making/rsc#42]
I use this jar error on Win10.

Error message:
joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option [arguments], but you asked for only one

my command:
java -jar rsc-0.6.1.jar tcp://localhost:4100 --request --route "api.search" -d '{"aa": "bb", "cc": "dd", "ee": "ff", "gg": "hh", "ii": "jj"}' --debug

**Comment by making** [comment]
What terminal are you using?
I'm not a windows user but I remember `'` didn't work in command prompt.

Try with `-d "{\"aa\": \"bb\", \"cc\": \"dd\", \"ee\": \"ff\", \"gg\": \"hh\", \"ii\": \"jj\"}"`

**Comment by Huang-ChenGang** [comment]
My terminal is cmd.
Your answer is works.
Thank you!
