### ISSUE TITLE
Is there composite metadata support in SETUP frame ?

### ISSUE THREAD

**Issue by peter-natkaniec** [making/rsc#45]
There are examples for both features, what about their combination ?

**Comment by making** [comment]
Not supported. What's your usecase?
Are you able to achieve that using other clients like `RSocketRequester` of spring ?

**Comment by sebczu** [comment]
we create connection in spring like this:
```
RSocketRequester.Builder builder;
builder
       .setupRoute("test")
       .setupData("example data")
       .setupMetadata("token jwt",MimeTypeUtils.parseMimeType(WellKnownMimeType.MESSAGE_RSOCKET_AUTHENTICATION.getString()))
       .dataMimeType(MimeTypeUtils.TEXT_PLAIN)
       .connectWebSocket(URI.create("ws://host"))
       .block();
```
can we achieve this same by `rsc`?
I suppose in `rsc` not exist equivalent for method `setupRoute`

**Comment by peter-natkaniec** [comment]
I have a spring boot app,  it's a gateway with web API , because of that I use web sockets. My API is protected by bearer (jwt) token. Spring security rsocket use composite medatada https://github.com/spring-projects/spring-security/blob/master/rsocket/src/main/java/org/springframework/security/rsocket/authentication/AuthenticationPayloadExchangeConverter.java. I planned to make some smoke tests using rsc to verify if deploy goes fine.  But I can't create proper setup message using rsc so far

**Comment by making** [comment]
Ok, I’ll look into it so that rsc can provide same experience as spring

**Comment by making** [comment]
@sebczu 
Did you try this example? https://github.com/making/rsc#authentication

**Comment by making** [comment]
>        .setupMetadata("token jwt",MimeTypeUtils.parseMimeType(WellKnownMimeType.MESSAGE_RSOCKET_AUTHENTICATION.getString()))

Is this your case? It's not using a composite metadata and `rsc` already supported [authentication](https://github.com/making/rsc#authentication).

**Comment by peter-natkaniec** [comment]
We solve problem changing server API, at the beginning **setup frame had dedicated custom route**. When we change the logic on server and map all connections without route to this controller then composite key in request metadata became redundant. I think this case require some explenation is spring-security-rsocket doc. 

```java
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.messaging.rsocket.RSocketRequester;
import org.springframework.messaging.rsocket.annotation.ConnectMapping;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.stereotype.Controller;
import reactor.core.publisher.Mono;

@Controller
public class SetupConnectionController  {

  @ConnectMapping
  public void setup(@AuthenticationPrincipal Mono<Jwt> player, RSocketRequester requester) {
    player.flatMap(...).subscribe();
  }
```

Now we are able to create request using rsc with authentication to any route :

rsc ws://host/path \
  --setupMetadata "bearer:tokenJWT" \
  --setupMetadataMimeType "message/x.rsocket.authentication.v0" \
  --route "foo" \
  --data '{"foo": "boo"}'

**Comment by spencergibb** [comment]
Composite will be needed for rsocket routing broker

**Comment by making** [comment]
Thanks! I’ll work this in #30
