### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by ghahramani** [making/rsc#83]
Hi,

I am getting the error below when I try to call rsocket server with TLS enabled

```
Error: java.nio.channels.ClosedChannelException
```

**Comment by making** [comment]
Can you elaborate on the situation? What command did you run?
rsc supports (trusted) TLS.

Adding --trustCert option is already merged for self-signed certificates. It's ready to release.
https://github.com/making/rsc/pull/74

**Comment by ghahramani** [comment]
Thank you for the reply. I have a secured rsocket server managed by spring boot rsocket. It is running on my self-signed certification. I got the error when I call my server via rsc. do you have an example how can I use the --trustCert? It is not documented I believe.

**Comment by making** [comment]
@ghahramani It is not yet released but you can try it with a snapshot build 
https://github.com/making/rsc/suites/2073235556/artifacts/41940488


```
rsc --trustCert <your CA PEM file> ... tcp+tls://localhost:8080 or wss://localhost:8080
```

https://github.com/making/rsc-e2e/blob/tls/src/test/java/am/ik/rsocket/uppercase/UppercaseTlsControllerTests.java#L33
is my end-to-end test code

**Comment by ghahramani** [comment]
Ah, great, I will test it. When would you be able to release it?

**Comment by making** [comment]
I'm planning to cut a new release after [spring-aot-maven-plugin](https://github.com/spring-projects-experimental/spring-native) 0.9.0 is released

**Comment by making** [comment]
It's been released
https://github.com/making/rsc/releases/tag/0.9.0
