### ISSUE TITLE
【Q&A】`scoop install rsc` do not work 

### ISSUE THREAD

**Issue by sangjiexun** [making/rsc#90]
![Fig.1](https://user-images.githubusercontent.com/59449516/112406100-7bdd5380-8d4e-11eb-8c79-cae360fffdbf.png)

**Comment by making** [comment]
Did you follow the document?
https://github.com/making/rsc#install-via-scoop-windows

**Comment by sangjiexun** [comment]
> Did you follow the document?
> https://github.com/making/rsc#install-via-scoop-windows

THX !!!
[Fix] my `DNS reset 8.8.8.8` can use it now
![image](https://user-images.githubusercontent.com/59449516/112411913-99171f80-8d58-11eb-9b17-94d868c5b4b8.png)
