### ISSUE TITLE
Support websocket endpoints

### ISSUE THREAD

**Issue by Polve** [making/rsc#98]
The rsocket endpoint can be used over websockets (the standard for web application), but I can't use rsc to debug them because I get this error:

> java.lang.IllegalArgumentException: http is unsupported scheme.

The example endpoint I wanted to debug is http://localhost:8080/rsocket

**Comment by making** [comment]
Use ws://localhost:8080/rsocket 
https://github.com/making/rsc#example-usages

**Comment by Polve** [comment]
WTH how could I miss it.

Thanks
